# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--uvAzjV3uXUTuMUyKyU2KXOZITDibMr
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile sabrinafirstapp.py
# import streamlit as st
# import numpy as np
# import pandas as pd
# 
# st.header("My first Streamlit App")
# st.write(pd.DataFrame({
#     'Intplan': ['yes', 'yes', 'yes', 'no'],
#     'Churn Status': [0, 0, 0, 1]
# }))